name: 'Setup Lazarus - fpcup'
description: 'Setup Lazarus using fpcup'
inputs:
  laz-branch: 
    required: false
  fpc-branch: 
    required: false
  laz-revision: 
    required: false
  fpc-revision: 
    required: false
  fpcup-release:
    required: true
runs:
  using: 'node12'
  main: 'dist/index/index.js'
  post: 'dist/post/index.js'
  post-if: env.SAVE_CACHE_KEY != ''

