name: Test Revision

on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
      
jobs:
  test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        config:            
          - name: Windows 64
            os: windows-latest
            args: --os=win64 --cpu=x86_64
            
          - name: Windows 32  
            os: windows-latest
            args: --os=win32 --cpu=i386

          - name: Linux 64
            os: ubuntu-latest
            args: --os=linux --cpu=x86_64
            
          - name: AArch64  
            os: ubuntu-latest
            args: --os=linux --cpu=aarch64
            
          - name: MacOS 64
            os: macos-latest
            args: --os=darwin --cpu=x86_64 --widgetset=cocoa
            
    steps:
      - uses: actions/checkout@v2.3.4
      
      - name: Install Lazarus
        uses: ./
        with:
          laz-revision: 87130707e7b820ae7167900041f9ea21087f2015 # lazarus 2_0_12
          fpc-revision: f42f55aed84027529828dbb762e2094f7e547394 # release 3_2_0
          fpcup-release: v2.2.0h
      
      - name: Build Test
        run: |
          lazbuild ${{ matrix.config.args }} test_lazarus.lpi
          
      - name: Run Test
        if: matrix.config.name != 'AArch64' # AArch64 was cross compiled
        run: |
          ./test
