name: Test Revision

on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
      
jobs:
  test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        config:            
          - name: Windows 64
            os: windows-latest
            
          - name: Windows 32  
            os: windows-latest
            args: --os=win32 --cpu=i386

          - name: Linux 64
            os: ubuntu-latest
          
          - name: AArch64  
            os: ubuntu-latest
            args: --cpu=aarch64
            
          - name: MacOS 64
            os: macos-latest
            args: --widgetset=cocoa
            
    steps:
      - uses: actions/checkout@v2.3.4
      
      - name: Install Lazarus
        uses: ./
        with:
          laz-revision: 58bab5263932362aa35a59bf0cd9439dfe87b25c
          fpc-revision: 6e6c946e0fd1765f99110e12c79db27a400c6587
          fpcup-release: v2.2.0c
      
      - name: Build Test
        run: |
          lazbuild ${{ matrix.config.args }} test_lazarus.lpi
          
      - name: Run Test
        if: matrix.config.name != 'AArch64' # AArch64 was cross compiled
        run: |
          ./test
